### ISSUE TITLE
Размещение на gh-pages

### ISSUE THREAD

**Issue by shanhaichik** [fual/holy-js#1]
Публикуй свои презентации сразу на gh-pages. Так будет и доступ проще смотреть и делиться! 
Да и вообще, стильно, модно, молодежно :smile:

**Comment by fual** [comment]
согласен Но я эту пока не доделал Доделаю - отправлю.
Запушил чтобы не потерять

**Comment by fual** [comment]
Пока можете посмотреть -http://fual.github.io/custom-properties/

**Comment by fual** [comment]
https://fual.github.io/holy-js/
